Development utilties
n-claes/legolas pull request #78
Opened 2021-09-13 13:36 UTC by elecprog

This pull request contains three main changes (in separate commits, allowing cherrypicking if needed) to aid development.

1. Changes `buildlegolas.sh` to build in release mode by default, adding the `debug` option for previous behaviour.
2. Adds an `assert(condition)` macro for sanity checks that should be disabled for a release build.
3. Adds `tic([start_time])` and `toc(message, [start_time])` for simple timing.

I hope I didn't miss any requirements. None of these have unit tests, as they only have side effects, but all have been manually verified and should work.

2021-09-14 08:13 UTC, n-claes requested changes
LGTM, just a few minor nitpicky comments.

Also, apparently cmake's "default" (what we had before) setting disables optimisations and hence ignores some warnings (see [here](https://stackoverflow.com/questions/57082513/gcc-warnings-not-detected-in-cmake-debug-builds-but-detected-in-release-ones)). Compiling in release mode throws a few warnings that went unnoticed up to now. So if you allow edits from maintainers I'll push a few tiny module edits which fix the release build warnings.

2021-09-14 08:13 UTC, n-claes commented on src/utils/mod_timing.f08
> +  use mod_logging, only: log_message
```suggestion
  use mod_logging, only: log_message, str
```

2021-09-14 08:13 UTC, n-claes commented on src/utils/mod_timing.f08
> +    call log_message(message // " (" // trim(time_str) // " s)", level="debug")
Use `str` here and remove character writing, provide an optional formatting argument `fmt=` if needed

2021-09-14 08:13 UTC, n-claes commented on src/utils/mod_timing.f08
> +    call log_message(message // " (" // trim(time_str) // " s CPU)", level="debug")
same comment as above

2021-09-14 10:32 UTC, elecprog commented on src/utils/mod_assert.f08
> +    end if
I seem to have missed that, changed throughout as of latest commit.

2021-09-15 07:29 UTC, n-claes approved these changes

2021-09-15 07:59 UTC, merged